import { baseConfig } from '@n8n/eslint-config/base';

export default [
	...baseConfig,
	{
		// Root-level configuration for monorepo
		files: ['**/*.{js,mjs,ts}'],
		ignores: [
			'node_modules/**',
			'dist/**',
			'build/**',
			'coverage/**',
			'**/node_modules/**',
			'**/dist/**',
			'**/build/**',
			'**/coverage/**',
			'packages/**/node_modules/**',
			'packages/**/dist/**',
			'packages/**/build/**',
			'packages/**/coverage/**',
			'chrome-*/**',
			'ui-test-*/**',
			'temp/**',
			'logs/**',
			'screenshots/**',
			'.turbo/**',
			'.git/**',
			'.vscode/**',
			'patches/**',
			'scripts/**/*.mjs',
			'*.config.js',
			'*.config.mjs',
			'jest.config.js',
			'cypress.config.js',
			'vitest.config.ts',
			'vite.config.ts',
			'turbo.json',
			'tsconfig*.json',
			'lefthook.yml',
			'renovate.json',
			'pnpm-*.yaml',
			'*.log',
			'*.pid',
			'TODO.json*',
			'CHANGELOG.md',
			'CLAUDE*.md',
			'*.test.js',
			'*.test.ts',
			'test*.js',
			'*test*.cjs',
			'*browser*.js',
			'*ui-test*.js',
			'*playwright*.js',
			'*puppeteer*.js',
			'*screenshot*.js',
			'*comprehensive*.js',
			'api-test.js',
			'final*.js',
			'manual*.js',
			'simple*.js',
			'detailed*.js',
			'master*.js',
		],
		rules: {
			// Global rules for the entire monorepo
			'no-console': ['warn', { allow: ['warn', 'error'] }],
			'no-debugger': 'error',
			'prefer-const': 'error',
			'no-var': 'error',
			
			// Enhanced code quality rules
			'no-unused-vars': ['error', { argsIgnorePattern: '^_', varsIgnorePattern: '^_' }],
			'no-duplicate-imports': 'error',
			'no-unreachable': 'error',
			'no-unreachable-loop': 'error',
			'no-unsafe-optional-chaining': 'error',
			'no-unused-private-class-members': 'error',
			'prefer-arrow-callback': 'error',
			'prefer-template': 'error',
			'prefer-spread': 'error',
			'prefer-destructuring': ['error', { array: false, object: true }],
			'no-implicit-coercion': 'error',
			'no-magic-numbers': ['warn', { ignore: [-1, 0, 1, 2] }],
			'complexity': ['warn', { max: 15 }],
			'max-depth': ['warn', { max: 4 }],
			'max-params': ['warn', { max: 4 }],
			'max-lines-per-function': ['warn', { max: 250, skipBlankLines: true, skipComments: true }],
			
			// Security rules
			'no-eval': 'error',
			'no-implied-eval': 'error',
			'no-new-func': 'error',
			'no-script-url': 'error',
			
			// Performance rules
			'no-loop-func': 'error',
			'no-await-in-loop': 'warn',
		},
	},
	{
		// Specific overrides for root-level files
		files: ['*.{js,mjs,ts}'],
		rules: {
			'@typescript-eslint/no-var-requires': 'off',
			'import-x/no-default-export': 'off',
		},
	},
];