import { baseConfig } from '@n8n/eslint-config/base';

export default [
	...baseConfig,
	{
		// Root-level configuration for monorepo
		files: ['**/*.{js,mjs,ts}'],
		ignores: [
			'node_modules/**',
			'dist/**',
			'build/**',
			'coverage/**',
			'**/node_modules/**',
			'**/dist/**',
			'**/build/**',
			'**/coverage/**',
			'packages/**/node_modules/**',
			'packages/**/dist/**',
			'packages/**/build/**',
			'packages/**/coverage/**',
			'chrome-*/**',
			'ui-test-*/**',
			'temp/**',
			'logs/**',
			'screenshots/**',
			'.turbo/**',
			'.git/**',
			'.vscode/**',
			'patches/**',
			'scripts/**/*.mjs',
			'*.config.js',
			'*.config.mjs',
			'jest.config.js',
			'cypress.config.js',
			'vitest.config.ts',
			'vite.config.ts',
			'turbo.json',
			'tsconfig*.json',
			'lefthook.yml',
			'renovate.json',
			'pnpm-*.yaml',
			'*.log',
			'*.pid',
			'TODO.json*',
			'CHANGELOG.md',
			'CLAUDE*.md',
			'*.test.js',
			'*.test.ts',
			'test*.js',
			'*test*.cjs',
			'*browser*.js',
			'*ui-test*.js',
			'*playwright*.js',
			'*puppeteer*.js',
			'*screenshot*.js',
			'*comprehensive*.js',
			'api-test.js',
			'final*.js',
			'manual*.js',
			'simple*.js',
			'detailed*.js',
			'master*.js',
		],
		rules: {
			// Global rules for the entire monorepo
			'no-console': ['warn', { allow: ['warn', 'error'] }],
			'no-debugger': 'error',
			'prefer-const': 'error',
			'no-var': 'error',
		},
	},
	{
		// Specific overrides for root-level files
		files: ['*.{js,mjs,ts}'],
		rules: {
			'@typescript-eslint/no-var-requires': 'off',
			'import-x/no-default-export': 'off',
		},
	},
];